//
// Generated file, do not edit! Created by opp_msgc 4.4 from EtherFrame.msg.
//

#ifndef _ETHERFRAME_M_H_
#define _ETHERFRAME_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>EtherFrame.msg</tt> by opp_msgc.
 * <pre>
 * message EtherFrame
 * {
 *     @customize(true);
 *     char data[1514];
 * }
 * </pre>
 *
 * EtherFrame_Base is only useful if it gets subclassed, and EtherFrame is derived from it.
 * The minimum code to be written for EtherFrame is the following:
 *
 * <pre>
 * class EtherFrame : public EtherFrame_Base
 * {
 *   private:
 *     void copy(const EtherFrame& other) { ... }

 *   public:
 *     EtherFrame(const char *name=NULL, int kind=0) : EtherFrame_Base(name,kind) {}
 *     EtherFrame(const EtherFrame& other) : EtherFrame_Base(other) {copy(other);}
 *     EtherFrame& operator=(const EtherFrame& other) {if (this==&other) return *this; EtherFrame_Base::operator=(other); copy(other); return *this;}
 *     virtual EtherFrame *dup() const {return new EtherFrame(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from EtherFrame_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(EtherFrame);
 * </pre>
 */
class EtherFrame_Base : public ::cMessage
{
  protected:
    char data_var[1514];

  private:
    void copy(const EtherFrame_Base& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const EtherFrame_Base&);
    // make constructors protected to avoid instantiation
    EtherFrame_Base(const char *name=NULL, int kind=0);
    EtherFrame_Base(const EtherFrame_Base& other);
    // make assignment operator protected to force the user override it
    EtherFrame_Base& operator=(const EtherFrame_Base& other);

  public:
    virtual ~EtherFrame_Base();
    virtual EtherFrame_Base *dup() const {throw cRuntimeError("You forgot to manually add a dup() function to class EtherFrame");}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getDataArraySize() const;
    virtual char getData(unsigned int k) const;
    virtual void setData(unsigned int k, char data);
};


#endif // _ETHERFRAME_M_H_
